name: eugpark
favicon: null
layout_spectrum: 0.60208
typography_spectrum: 0.73163
title: Eugene Park
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.11700704414397478
  lightness: 0.7307556855957955
  saturation: 0.3358424319885671
  rhythmicContrast: 0.22835753276012838
purpose: []
